[build]
  functions = "functions"  # Thư mục chứa các serverless function
  # publish = "public"  # Không cần dòng này nếu không có thư mục public

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
